@rootUrl = http://localhost:5000/api



### Create New Normal User
POST {{rootUrl}}/users/register
Content-Type: application/json

{
  "fullName": "Bhavesh User",
  "email": "Bhavesh.user@example.com",
  "password": "BhaveshSadhu@123",
  "phone": "0413221234",
  "role": "user",
  "address": {
    "street": "12 Test Street",
    "city": "Wollongong",
    "state": "NSW",
    "postalCode": "2500",
    "country": "Australia"
  },
  "avatar": ""
}

### Create New Vendor
POST {{rootUrl}}/users/register
Content-Type: application/json

{
  "fullName": "Vendor Owner",
  "email": "vendor@example.com",
  "password": "Vendor@123",
  "phone": "0411222333",
  "role": "vendor",
  "shopName": "Test Vendor Store",
  "shopDetails": "We sell test products online",
  "address": {
    "street": "50 Market Road",
    "city": "Sydney",
    "state": "NSW",
    "postalCode": "2000",
    "country": "Australia"
  }
}


### Create New Delivery Partner
POST {{rootUrl}}/users/register
Content-Type: application/json

{
  "fullName": "Delivery Rider",
  "email": "rider@example.com",
  "password": "Rider@123",
  "phone": "0411333444",
  "role": "delivery",
  "vehicleType": "bike",
  "licenseNumber": "DL-NSW-123456",
  "address": {
    "street": "22 Rider Lane",
    "city": "Sydney",
    "state": "NSW",
    "postalCode": "2001",
    "country": "Australia"
  }
}


### Create Admin User
POST {{rootUrl}}/users/register
Content-Type: application/json

{
  "fullName": "Main Admin",
  "email": "admin@example.com",
  "password": "Admin@123",
  "phone": "0411999888",
  "role": "admin"
}

############################################
### USER LOGIN (GET COOKIE TOKEN)
############################################
### USER LOGIN
# @name login
POST {{rootUrl}}/users/login
Content-Type: application/json

{
  "email": "Bhavesh.user@example.com",
  "password": "BhaveshSadhu@123"
}

### GET USER PROFILE
GET {{rootUrl}}/users/profile
Cookie: token={{login.response.cookies.token}}

### UPDATE USER PROFILE
PUT {{rootUrl}}/users/profile
Content-Type: application/json
Cookie: token={{login.response.cookies.token}}

{
  "name": "Updated Name",
  "phone": "0400000000",
  "address": {
    "street": "10 Updated St",
    "city": "Sydney",
    "state": "NSW",
    "postalCode": "2000",
    "country": "Australia"
  }
}
### DELETE USER ACCOUNT
DELETE {{rootUrl}}/users/deleteuser
Cookie: token={{login.response.cookies.token}}

### LOGOUT USER
POST {{rootUrl}}/users/logout
Cookie: token={{login.response.cookies.token}}
